name: test-with-setup-sigstore-env

on:
  push:
    branches:
      - main
      - series/*
  pull_request:
  schedule:
    - cron: '0 12 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        # TODO: use new release
        - id: setup-sigstore-env
          uses: sigstore/scaffolding/actions/setup-sigstore-env@c1697866accfa0fbe21caf7e16ab85f236695428  # main
        - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
          with:
            persist-credentials: false
        - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
          with:
            # use the version specified by this project.
            python-version-file: pyproject.toml
            allow-prereleases: true
            cache: "pip"
            cache-dependency-path: pyproject.toml
        - run: |
            export TEST_SETUP_SIGSTORE_ENV="any non-empty value"
            export SIGSTORE_IDENTITY_TOKEN_local=$( cat ${{ steps.setup-sigstore-env.outputs.oidc-token }} )
            export TRUST_CONFIG=${{ steps.setup-sigstore-env.outputs.trust-config }}

            set -o pipefail
            make test TEST_ARGS=" -rs -vv" | tee output
            ! grep -q "skipping test that use the local environment" output || (echo "ERROR: Found skip message" && exit 1)
