name: test-with-setup-sigstore-env

on:
  push:
    branches:
      - main
      - series/*
  pull_request:
  schedule:
    - cron: '0 12 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - uses: sigstore/scaffolding/actions/setup-sigstore-env@main
        - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
          with:
            persist-credentials: false
        - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
          with:
            python-version: 3.9
            allow-prereleases: true
            cache: "pip"
            cache-dependency-path: pyproject.toml
        - env:
            TEST_SETUP_SIGSTORE_ENV: true 
          run: make test TEST_ARGS="-k test_sign_prehashed_rekorv2"